language: python
python:
    - "3.7"
    
dist: xenial

os:
  - linux
  
addons:
  apt:
    packages:
    - gfortran


env: FC=gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - py.test