language: python
python:
    - "3.7"
    
dist: xenial

os:
  - linux

env: FC=gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

install:
    - "sudo apt-get update"
    - "sudo apt-get install python-numpy gfortran"
    - "python setup.py build "
    - "python setup.py install"
  
script:
    - py.test