language: python

python:
    - "3.7"
    
os:
  - linux

env: FC=gfortran


before_install:
    - "sudo apt-get update"
    - "sudo apt-get install python-numpy gfortran"

install:
    - "python setup.py build"
    - "python setup.py install"


script:
    - "python ./genericf2py/main.py"