language: python
python:
    - "3.7"

os:
  - linux
  
addons:
  apt_packages:
    - gfortran


env: FC=gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y gfortran libblas-dev liblapack-dev;
      sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

install:
    - pip install -r requirements.txt
    - pip install .

script:
    - py.test