language: python
python:
    - "2.7"
    - "3.7"

os:
  - linux
  
addons:
  apt_packages:
    - gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

install:
    - pip install -r requirements.txt
    - pip install .
script:
    - py.test