language: python
python:
    - "3.7"
    
dist: xenial

os:
  - linux
  
addons:
  apt:
    packages:
    - gfortran


env: FC=gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        - sudo apt-get install libblas-dev liblapack-dev
        - sudo apt-get install libopenmpi-dev openmpi-bin # libhdf5-openmpi-dev
    fi

install:
    - "sudo apt-get update"
    - "sudo apt-get install python-numpy gfortran"
    - "pip install numpy"
    - "python setup.py install"
  
script:
    - py.test