
matrix:
  include:
  - os: windows

    name: Windows Check
    language: minimal
        
    env: FC=gfortran

    before_install:
        - "choco install python --version 3.7.2"
        - "choco install mingw"
        - "export PATH="/c/Python37:/c/Python37/Scripts:$PATH""

install:
    - "python setup.py build"
    - "python setup.py install"

script:
    - "python ./genericf2py/main.py"