language: python
python:
    - "3.7"
    
dist: xenial

os:
  - linux
  
addons:
  apt:
    packages:
    - gfortran


env: FC=gfortran


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install gcc;
    fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        - sudo apt-get install libblas-dev liblapack-dev
        - sudo apt-get install libopenmpi-dev openmpi-bin # libhdf5-openmpi-dev
    fi

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - py.test